/* Generated by AN DISI Unibo */ 
package it.unibo.firefly2

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Firefly2 ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		        var StartTime = 0L
		        var BlinkTime = 800L 
		        var SyncTime  = 1000L
		        var IsSynced  = false
		        var AlignTime = 0L
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblack("$name | start")
						 StartTime = System.currentTimeMillis()  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="flashOn", cond=doswitch() )
				}	 
				state("flashOn") { //this:State
					action { //it:State
						 var Elapsed = System.currentTimeMillis() - StartTime  
						if(  Elapsed > 10000 && !IsSynced  
						 ){ 
						               IsSynced = true 
						               AlignTime = SyncTime - (System.currentTimeMillis() % SyncTime)
						CommUtils.outblack("$name | Sincronizzazione attivata! Allineamento fase in $AlignTime ms")
						delay(AlignTime)
						 BlinkTime = SyncTime  
						}
						CommUtils.outmagenta("$name | turnOn (delay=$BlinkTime)")
						forward("cellstate", "cellstate(12,11,1)" ,"griddisplay" ) 
						delay(BlinkTime)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="flashOff", cond=doswitch() )
				}	 
				state("flashOff") { //this:State
					action { //it:State
						CommUtils.outcyan("$name | turnOff")
						forward("cellstate", "cellstate(12,11,0)" ,"griddisplay" ) 
						delay(BlinkTime)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="flashOn", cond=doswitch() )
				}	 
			}
		}
} 
